/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v0/forecast": {
    /** Forecast */
    get: operations["forecast_api_v0_forecast_get"];
  };
  "/api/v0/packing_lists": {
    /** Get Packing Lists */
    get: operations["get_packing_lists_api_v0_packing_lists_get"];
  };
  "/api/v0/packing_list/{packing_list_id}": {
    /** Get Packing List */
    get: operations["get_packing_list_api_v0_packing_list__packing_list_id__get"];
    /** Update Packing List */
    post: operations["update_packing_list_api_v0_packing_list__packing_list_id__post"];
    /** Remove Packing List */
    delete: operations["remove_packing_list_api_v0_packing_list__packing_list_id__delete"];
  };
  "/api/v0/packing_list": {
    /** Create Packing List */
    post: operations["create_packing_list_api_v0_packing_list_post"];
  };
  "/api/v0/trip_plans": {
    /** Get Trip Plans */
    get: operations["get_trip_plans_api_v0_trip_plans_get"];
  };
  "/api/v0/trip_plan/{trip_plan_id}": {
    /** Get Trip Plan */
    get: operations["get_trip_plan_api_v0_trip_plan__trip_plan_id__get"];
    /** Remove Trip Plan */
    delete: operations["remove_trip_plan_api_v0_trip_plan__trip_plan_id__delete"];
    /** Update Trip Plan */
    patch: operations["update_trip_plan_api_v0_trip_plan__trip_plan_id__patch"];
  };
  "/api/v0/trip_plan": {
    /** Create Trip Plan */
    post: operations["create_trip_plan_api_v0_trip_plan_post"];
  };
  "/api/v0/partners": {
    /** List */
    get: operations["partners_api_v0_partners_get"];
  };
  "/api/v0/partner": {
    /** Add Partner */
    post: operations["add_partner_api_v0_partner_post"];
  };
  "/api/v0/partner/{partner_id}": {
    /** Remove Partner */
    delete: operations["remove_partner_api_v0_partner__partner_id__delete"];
  };
  "/api/v0/access_key": {
    /** Create Access Key */
    post: operations["create_access_key_api_v0_access_key_post"];
  };
  "/api/v0/userinfo": {
    /** Userinfo */
    get: operations["userinfo_api_v0_userinfo_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AccessKeyRequest */
    AccessKeyRequest: {
      /** Token */
      token: string;
    };
    /** Avalanche */
    Avalanche: {
      /** Title */
      title: string;
      /** Date Issued */
      date_issued: string;
      /** Valid Until */
      valid_until: string;
      /** Forecaster */
      forecaster: string;
      /** Summary */
      summary: string;
      /** Layers */
      layers: components["schemas"]["AvalancheForecastLayer"][];
      /** Confidence */
      confidence: string;
      /** Advice */
      advice: string[];
    };
    /** AvalancheForecastLayer */
    AvalancheForecastLayer: {
      /** Date */
      date: string;
      /** Alpine Rating */
      alpine_rating: string;
      /** Treeline Rating */
      treeline_rating: string;
      /** Below Treeline Rating */
      below_treeline_rating: string;
    };
    /** Forecast */
    Forecast: {
      avalanche?: components["schemas"]["Avalanche"];
      weather: components["schemas"]["WeatherForecast"];
    };
    /** Geometry */
    Geometry: {
      /** Type */
      type: string;
      /** Coordinates */
      coordinates: number[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** PackingListRequest */
    PackingListRequest: {
      /** Name */
      name: string;
      /** Contents */
      contents: Record<string, never>[];
    };
    /** Properties */
    Properties: {
      /** Meta */
      meta: Record<string, never>;
      /** Timeseries */
      timeseries: components["schemas"]["TimeSeriesData"][];
    };
    /** TimeSeriesData */
    TimeSeriesData: {
      /** Time */
      time: string;
      /** Data */
      data: {
        [key: string]: components["schemas"]["TimeSeriesDatum"];
      };
    };
    /** TimeSeriesDatum */
    TimeSeriesDatum: {
      /**
       * Details
       * @default {}
       */
      details?: components["schemas"]["TimeSeriesDatumDetails"];
      /**
       * Summary
       * @default {}
       */
      summary?: {
        [key: string]: string;
      };
    };
    /** TimeSeriesDatumDetails */
    TimeSeriesDatumDetails: {
      /**
       * Air Pressure At Sea Level
       * @default 0
       */
      air_pressure_at_sea_level?: number;
      /**
       * Air Temperature
       * @default 0
       */
      air_temperature?: number;
      /**
       * Cloud Area Fraction
       * @default 0
       */
      cloud_area_fraction?: number;
      /**
       * Relative Humidity
       * @default 0
       */
      relative_humidity?: number;
      /**
       * Wind From Direction
       * @default 0
       */
      wind_from_direction?: number;
      /**
       * Wind Speed
       * @default 0
       */
      wind_speed?: number;
      /**
       * Precipitation Amount
       * @default 0
       */
      precipitation_amount?: number;
    };
    /** TripPlanDate */
    TripPlanDate: {
      /** Type */
      type: string;
      /** Dates */
      dates?: string | string[];
    };
    /** TripPlanRequest */
    TripPlanRequest: {
      /** Name */
      name: string;
      dates?: components["schemas"]["TripPlanDate"];
      /** People */
      people: (string | Record<string, never>)[];
      /** Trails */
      trails: string[];
      /** Itinerary */
      itinerary: unknown[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WeatherForecast */
    WeatherForecast: {
      /** Type */
      type: string;
      geometry: components["schemas"]["Geometry"];
      properties: components["schemas"]["Properties"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Forecast */
  forecast_api_v0_forecast_get: {
    parameters: {
      query?: {
        lat?: number;
        lng?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Forecast"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Packing Lists */
  get_packing_lists_api_v0_packing_lists_get: {
    parameters: {
      header: {
        "access-key": string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Packing List */
  get_packing_list_api_v0_packing_list__packing_list_id__get: {
    parameters: {
      path: {
        packing_list_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Packing List */
  update_packing_list_api_v0_packing_list__packing_list_id__post: {
    parameters: {
      header: {
        "access-key": string;
      };
      path: {
        packing_list_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PackingListRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove Packing List */
  remove_packing_list_api_v0_packing_list__packing_list_id__delete: {
    parameters: {
      header: {
        "access-key": string;
      };
      path: {
        packing_list_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Packing List */
  create_packing_list_api_v0_packing_list_post: {
    parameters: {
      header: {
        "access-key": string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Trip Plans */
  get_trip_plans_api_v0_trip_plans_get: {
    parameters: {
      header: {
        "access-key": string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Trip Plan */
  get_trip_plan_api_v0_trip_plan__trip_plan_id__get: {
    parameters: {
      header?: {
        "access-key"?: string;
      };
      path: {
        trip_plan_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove Trip Plan */
  remove_trip_plan_api_v0_trip_plan__trip_plan_id__delete: {
    parameters: {
      header: {
        "access-key": string;
      };
      path: {
        trip_plan_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Trip Plan */
  update_trip_plan_api_v0_trip_plan__trip_plan_id__patch: {
    parameters: {
      header: {
        "access-key": string;
      };
      path: {
        trip_plan_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TripPlanRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Trip Plan */
  create_trip_plan_api_v0_trip_plan_post: {
    parameters: {
      header: {
        "access-key": string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List */
  partners_api_v0_partners_get: {
    parameters: {
      header: {
        "access-key": string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Add Partner */
  add_partner_api_v0_partner_post: {
    parameters: {
      query: {
        email: string;
      };
      header: {
        "access-key": string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove Partner */
  remove_partner_api_v0_partner__partner_id__delete: {
    parameters: {
      header: {
        "access-key": string;
      };
      path: {
        partner_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Access Key */
  create_access_key_api_v0_access_key_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccessKeyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Userinfo */
  userinfo_api_v0_userinfo_get: {
    parameters: {
      header: {
        "access-key": string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
