/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Triptracks);
  }
}(this, function(expect, Triptracks) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Triptracks.Alerts();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Alerts', function() {
    it('should create an instance of Alerts', function() {
      // uncomment below and update the code to test Alerts
      //var instance = new Triptracks.Alerts();
      //expect(instance).to.be.a(Triptracks.Alerts);
    });

    it('should have the property advisories (base name: "advisories")', function() {
      // uncomment below and update the code to test the property advisories
      //var instance = new Triptracks.Alerts();
      //expect(instance).to.be();
    });

    it('should have the property endings (base name: "endings")', function() {
      // uncomment below and update the code to test the property endings
      //var instance = new Triptracks.Alerts();
      //expect(instance).to.be();
    });

    it('should have the property statements (base name: "statements")', function() {
      // uncomment below and update the code to test the property statements
      //var instance = new Triptracks.Alerts();
      //expect(instance).to.be();
    });

    it('should have the property warnings (base name: "warnings")', function() {
      // uncomment below and update the code to test the property warnings
      //var instance = new Triptracks.Alerts();
      //expect(instance).to.be();
    });

    it('should have the property watches (base name: "watches")', function() {
      // uncomment below and update the code to test the property watches
      //var instance = new Triptracks.Alerts();
      //expect(instance).to.be();
    });

  });

}));
