/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Triptracks);
  }
}(this, function(expect, Triptracks) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Triptracks.Avalanche();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Avalanche', function() {
    it('should create an instance of Avalanche', function() {
      // uncomment below and update the code to test Avalanche
      //var instance = new Triptracks.Avalanche();
      //expect(instance).to.be.a(Triptracks.Avalanche);
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new Triptracks.Avalanche();
      //expect(instance).to.be();
    });

    it('should have the property dateIssued (base name: "date_issued")', function() {
      // uncomment below and update the code to test the property dateIssued
      //var instance = new Triptracks.Avalanche();
      //expect(instance).to.be();
    });

    it('should have the property validUntil (base name: "valid_until")', function() {
      // uncomment below and update the code to test the property validUntil
      //var instance = new Triptracks.Avalanche();
      //expect(instance).to.be();
    });

    it('should have the property forecaster (base name: "forecaster")', function() {
      // uncomment below and update the code to test the property forecaster
      //var instance = new Triptracks.Avalanche();
      //expect(instance).to.be();
    });

    it('should have the property summary (base name: "summary")', function() {
      // uncomment below and update the code to test the property summary
      //var instance = new Triptracks.Avalanche();
      //expect(instance).to.be();
    });

    it('should have the property layers (base name: "layers")', function() {
      // uncomment below and update the code to test the property layers
      //var instance = new Triptracks.Avalanche();
      //expect(instance).to.be();
    });

    it('should have the property confidence (base name: "confidence")', function() {
      // uncomment below and update the code to test the property confidence
      //var instance = new Triptracks.Avalanche();
      //expect(instance).to.be();
    });

    it('should have the property advice (base name: "advice")', function() {
      // uncomment below and update the code to test the property advice
      //var instance = new Triptracks.Avalanche();
      //expect(instance).to.be();
    });

  });

}));
