/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Triptracks);
  }
}(this, function(expect, Triptracks) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Triptracks.HourlyForecast();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HourlyForecast', function() {
    it('should create an instance of HourlyForecast', function() {
      // uncomment below and update the code to test HourlyForecast
      //var instance = new Triptracks.HourlyForecast();
      //expect(instance).to.be.a(Triptracks.HourlyForecast);
    });

    it('should have the property condition (base name: "condition")', function() {
      // uncomment below and update the code to test the property condition
      //var instance = new Triptracks.HourlyForecast();
      //expect(instance).to.be();
    });

    it('should have the property iconCode (base name: "icon_code")', function() {
      // uncomment below and update the code to test the property iconCode
      //var instance = new Triptracks.HourlyForecast();
      //expect(instance).to.be();
    });

    it('should have the property period (base name: "period")', function() {
      // uncomment below and update the code to test the property period
      //var instance = new Triptracks.HourlyForecast();
      //expect(instance).to.be();
    });

    it('should have the property precipProbability (base name: "precip_probability")', function() {
      // uncomment below and update the code to test the property precipProbability
      //var instance = new Triptracks.HourlyForecast();
      //expect(instance).to.be();
    });

    it('should have the property temperature (base name: "temperature")', function() {
      // uncomment below and update the code to test the property temperature
      //var instance = new Triptracks.HourlyForecast();
      //expect(instance).to.be();
    });

  });

}));
