/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Triptracks);
  }
}(this, function(expect, Triptracks) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Triptracks.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('createAccessKeyApiV0AccessKeyPost', function() {
      it('should call createAccessKeyApiV0AccessKeyPost successfully', function(done) {
        //uncomment below and update the code to test createAccessKeyApiV0AccessKeyPost
        //instance.createAccessKeyApiV0AccessKeyPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createPackingListApiV0PackingListPost', function() {
      it('should call createPackingListApiV0PackingListPost successfully', function(done) {
        //uncomment below and update the code to test createPackingListApiV0PackingListPost
        //instance.createPackingListApiV0PackingListPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createTripPlanApiV0TripPlanPost', function() {
      it('should call createTripPlanApiV0TripPlanPost successfully', function(done) {
        //uncomment below and update the code to test createTripPlanApiV0TripPlanPost
        //instance.createTripPlanApiV0TripPlanPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('forecastApiV0ForecastGet', function() {
      it('should call forecastApiV0ForecastGet successfully', function(done) {
        //uncomment below and update the code to test forecastApiV0ForecastGet
        //instance.forecastApiV0ForecastGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPackingListApiV0PackingListPackingListIdGet', function() {
      it('should call getPackingListApiV0PackingListPackingListIdGet successfully', function(done) {
        //uncomment below and update the code to test getPackingListApiV0PackingListPackingListIdGet
        //instance.getPackingListApiV0PackingListPackingListIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPackingListsApiV0PackingListsGet', function() {
      it('should call getPackingListsApiV0PackingListsGet successfully', function(done) {
        //uncomment below and update the code to test getPackingListsApiV0PackingListsGet
        //instance.getPackingListsApiV0PackingListsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTripPlanApiV0TripPlanTripPlanIdGet', function() {
      it('should call getTripPlanApiV0TripPlanTripPlanIdGet successfully', function(done) {
        //uncomment below and update the code to test getTripPlanApiV0TripPlanTripPlanIdGet
        //instance.getTripPlanApiV0TripPlanTripPlanIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTripPlansApiV0TripPlansGet', function() {
      it('should call getTripPlansApiV0TripPlansGet successfully', function(done) {
        //uncomment below and update the code to test getTripPlansApiV0TripPlansGet
        //instance.getTripPlansApiV0TripPlansGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removePackingListApiV0PackingListPackingListIdDelete', function() {
      it('should call removePackingListApiV0PackingListPackingListIdDelete successfully', function(done) {
        //uncomment below and update the code to test removePackingListApiV0PackingListPackingListIdDelete
        //instance.removePackingListApiV0PackingListPackingListIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeTripPlanApiV0TripPlanTripPlanIdDelete', function() {
      it('should call removeTripPlanApiV0TripPlanTripPlanIdDelete successfully', function(done) {
        //uncomment below and update the code to test removeTripPlanApiV0TripPlanTripPlanIdDelete
        //instance.removeTripPlanApiV0TripPlanTripPlanIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePackingListApiV0PackingListPackingListIdPost', function() {
      it('should call updatePackingListApiV0PackingListPackingListIdPost successfully', function(done) {
        //uncomment below and update the code to test updatePackingListApiV0PackingListPackingListIdPost
        //instance.updatePackingListApiV0PackingListPackingListIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTripPlanApiV0TripPlanTripPlanIdPost', function() {
      it('should call updateTripPlanApiV0TripPlanTripPlanIdPost successfully', function(done) {
        //uncomment below and update the code to test updateTripPlanApiV0TripPlanTripPlanIdPost
        //instance.updateTripPlanApiV0TripPlanTripPlanIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userinfoApiV0UserinfoGet', function() {
      it('should call userinfoApiV0UserinfoGet successfully', function(done) {
        //uncomment below and update the code to test userinfoApiV0UserinfoGet
        //instance.userinfoApiV0UserinfoGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
