/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HourlyForecast model module.
 * @module model/HourlyForecast
 * @version 0.1.0
 */
class HourlyForecast {
    /**
     * Constructs a new <code>HourlyForecast</code>.
     * @alias module:model/HourlyForecast
     * @param condition {String} 
     * @param iconCode {String} 
     * @param period {Date} 
     * @param precipProbability {Number} 
     * @param temperature {Number} 
     */
    constructor(condition, iconCode, period, precipProbability, temperature) { 
        
        HourlyForecast.initialize(this, condition, iconCode, period, precipProbability, temperature);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, condition, iconCode, period, precipProbability, temperature) { 
        obj['condition'] = condition;
        obj['icon_code'] = iconCode;
        obj['period'] = period;
        obj['precip_probability'] = precipProbability;
        obj['temperature'] = temperature;
    }

    /**
     * Constructs a <code>HourlyForecast</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HourlyForecast} obj Optional instance to populate.
     * @return {module:model/HourlyForecast} The populated <code>HourlyForecast</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HourlyForecast();

            if (data.hasOwnProperty('condition')) {
                obj['condition'] = ApiClient.convertToType(data['condition'], 'String');
            }
            if (data.hasOwnProperty('icon_code')) {
                obj['icon_code'] = ApiClient.convertToType(data['icon_code'], 'String');
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'Date');
            }
            if (data.hasOwnProperty('precip_probability')) {
                obj['precip_probability'] = ApiClient.convertToType(data['precip_probability'], 'Number');
            }
            if (data.hasOwnProperty('temperature')) {
                obj['temperature'] = ApiClient.convertToType(data['temperature'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HourlyForecast</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HourlyForecast</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of HourlyForecast.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['condition'] && !(typeof data['condition'] === 'string' || data['condition'] instanceof String)) {
            throw new Error("Expected the field `condition` to be a primitive type in the JSON string but got " + data['condition']);
        }
        // ensure the json data is a string
        if (data['icon_code'] && !(typeof data['icon_code'] === 'string' || data['icon_code'] instanceof String)) {
            throw new Error("Expected the field `icon_code` to be a primitive type in the JSON string but got " + data['icon_code']);
        }

        return true;
    }


}

HourlyForecast.RequiredProperties = ["condition", "icon_code", "period", "precip_probability", "temperature"];

/**
 * @member {String} condition
 */
HourlyForecast.prototype['condition'] = undefined;

/**
 * @member {String} icon_code
 */
HourlyForecast.prototype['icon_code'] = undefined;

/**
 * @member {Date} period
 */
HourlyForecast.prototype['period'] = undefined;

/**
 * @member {Number} precip_probability
 */
HourlyForecast.prototype['precip_probability'] = undefined;

/**
 * @member {Number} temperature
 */
HourlyForecast.prototype['temperature'] = undefined;






export default HourlyForecast;

