/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PackingListRequest model module.
 * @module model/PackingListRequest
 * @version 0.1.0
 */
class PackingListRequest {
    /**
     * Constructs a new <code>PackingListRequest</code>.
     * @alias module:model/PackingListRequest
     * @param name {String} 
     * @param contents {Array.<Object>} 
     */
    constructor(name, contents) { 
        
        PackingListRequest.initialize(this, name, contents);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, contents) { 
        obj['name'] = name;
        obj['contents'] = contents;
    }

    /**
     * Constructs a <code>PackingListRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PackingListRequest} obj Optional instance to populate.
     * @return {module:model/PackingListRequest} The populated <code>PackingListRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PackingListRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('contents')) {
                obj['contents'] = ApiClient.convertToType(data['contents'], [Object]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PackingListRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PackingListRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PackingListRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['contents'])) {
            throw new Error("Expected the field `contents` to be an array in the JSON data but got " + data['contents']);
        }

        return true;
    }


}

PackingListRequest.RequiredProperties = ["name", "contents"];

/**
 * @member {String} name
 */
PackingListRequest.prototype['name'] = undefined;

/**
 * @member {Array.<Object>} contents
 */
PackingListRequest.prototype['contents'] = undefined;






export default PackingListRequest;

