/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Dates from './Dates';

/**
 * The TripPlanDate model module.
 * @module model/TripPlanDate
 * @version 0.1.0
 */
class TripPlanDate {
    /**
     * Constructs a new <code>TripPlanDate</code>.
     * @alias module:model/TripPlanDate
     * @param type {String} 
     * @param dates {module:model/Dates} 
     */
    constructor(type, dates) { 
        
        TripPlanDate.initialize(this, type, dates);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, dates) { 
        obj['type'] = type;
        obj['dates'] = dates;
    }

    /**
     * Constructs a <code>TripPlanDate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TripPlanDate} obj Optional instance to populate.
     * @return {module:model/TripPlanDate} The populated <code>TripPlanDate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TripPlanDate();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('dates')) {
                obj['dates'] = Dates.constructFromObject(data['dates']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TripPlanDate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TripPlanDate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TripPlanDate.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // validate the optional field `dates`
        if (data['dates']) { // data not null
          Dates.validateJSON(data['dates']);
        }

        return true;
    }


}

TripPlanDate.RequiredProperties = ["type", "dates"];

/**
 * @member {String} type
 */
TripPlanDate.prototype['type'] = undefined;

/**
 * @member {module:model/Dates} dates
 */
TripPlanDate.prototype['dates'] = undefined;






export default TripPlanDate;

