/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TripPlanDate from './TripPlanDate';

/**
 * The TripPlanRequest model module.
 * @module model/TripPlanRequest
 * @version 0.1.0
 */
class TripPlanRequest {
    /**
     * Constructs a new <code>TripPlanRequest</code>.
     * @alias module:model/TripPlanRequest
     * @param name {String} 
     */
    constructor(name) { 
        
        TripPlanRequest.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>TripPlanRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TripPlanRequest} obj Optional instance to populate.
     * @return {module:model/TripPlanRequest} The populated <code>TripPlanRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TripPlanRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('dates')) {
                obj['dates'] = TripPlanDate.constructFromObject(data['dates']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TripPlanRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TripPlanRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TripPlanRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `dates`
        if (data['dates']) { // data not null
          TripPlanDate.validateJSON(data['dates']);
        }

        return true;
    }


}

TripPlanRequest.RequiredProperties = ["name"];

/**
 * @member {String} name
 */
TripPlanRequest.prototype['name'] = undefined;

/**
 * @member {module:model/TripPlanDate} dates
 */
TripPlanRequest.prototype['dates'] = undefined;






export default TripPlanRequest;

